//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fubi_WPF_GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SampleRecognizers.xml")]
        public string LastRecognizerXMLPath {
            get {
                return ((string)(this["LastRecognizerXMLPath"]));
            }
            set {
                this["LastRecognizerXMLPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KeyMouseBindings.xml")]
        public string LastBindingXMLPath {
            get {
                return ((string)(this["LastBindingXMLPath"]));
            }
            set {
                this["LastBindingXMLPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("untitled.xml")]
        public string LastGenerateXMLPath {
            get {
                return ((string)(this["LastGenerateXMLPath"]));
            }
            set {
                this["LastGenerateXMLPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Fubi_WPF_GUI.SerializableStringDictionary ControlValues {
            get {
                return ((global::Fubi_WPF_GUI.SerializableStringDictionary)(this["ControlValues"]));
            }
            set {
                this["ControlValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trainingData/tempRecord.xml")]
        public string LastRecordingFilePath {
            get {
                return ((string)(this["LastRecordingFilePath"]));
            }
            set {
                this["LastRecordingFilePath"] = value;
            }
        }
    }
}
